- hosts: amazon2
  gather_facts: yes
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: apt -y update && apt install -y python-minimal
      sudo: yes
    - setup:
  vars:
    app_name: state_geonode 
    github_user: state-hiu
    server_name: dev.geonode.state.gov
    repo_name: State-GeoNode
    deploy_user: ubuntu
  roles:
     - { role: GeoNode.geonode }
